### ISSUE TITLE
The name 'GlobalConfiguration' does not exist in the current context

### ISSUE THREAD

**Issue by Yustie** [ninject/Ninject.Web.WebApi#14]
Hi,

After updating Ninject.Web.WebApi to version 3.2.4.0, I get this compiler error:

> The name 'GlobalConfiguration' does not exist in the current context.

And it's pointing to this line `GlobalConfiguration.Configure(WebApiConfig.Register);` in the global.asax.cs file.
Something wrong with the references/dependencies?

Edit:
I rolled back to the previous stable version and that works.

**Comment by scott-xu** [comment]
https://github.com/ninject/Ninject.Web.WebApi/blob/master/ReleaseNotes.md

Please install Ninject.Web.WebApi.WebHost

**Comment by Yustie** [comment]
Hi,

Thanks for your response. Shouldn't installing the latest stable version of Ninject.Web.WebApi install Ninject.Web.WebApi.WebHost automatically too since it depends on it?

Just wondering.

**Comment by scott-xu** [comment]
Ninject.Web.WebApi.WebHost, Ninject.Web.WebApi.OwinHost and Ninject.Web.WebApi.SelfHost depend on Ninject.Web.WebApi
