### ISSUE TITLE
update Microsoft.AspNet.WebApi to 5.2.3 then the DI  not work!

### ISSUE THREAD

**Issue by leshin** [ninject/Ninject.Web.WebApi#15]
{"Message":"出现错误。","ExceptionMessage":"尝试创建“UsersController”类型的控制器时出错。请确保控制器具有无参数公共构造函数。","ExceptionType":"System.InvalidOperationException","StackTrace":"   在 System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)\r\n   在 System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request)\r\n   在 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","InnerException":{"Message":"出现错误。","ExceptionMessage":"类型“Account.Api.Controllers.UsersController”没有默认构造函数","ExceptionType":"System.ArgumentException","StackTrace":"   在 System.Linq.Expressions.Expression.New(Type type)\r\n   在 System.Web.Http.Internal.TypeActivator.Create[TBase](Type instanceType)\r\n   在 System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator)\r\n   在 System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)"}}

**Comment by scott-xu** [comment]
WebHost的吗？你是怎么bootstrap起来的？

**Comment by scott-xu** [comment]
Please make sure you installed Ninject.Web.WebApi.WebHost

**Comment by leshin** [comment]
Ninject.Web.WebApi 3.2.4 无法注入。  3.2.3正常！！

**Comment by scott-xu** [comment]
麻烦提供详细的package列表

**Comment by leshin** [comment]
<packages>
  <package id="EntityFramework" version="6.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net45" />
  <package id="Ninject" version="3.2.2.0" targetFramework="net45" />
  <package id="Ninject.MVC5" version="3.2.1.0" targetFramework="net45" />
  <package id="Ninject.Web.Common" version="3.2.3.0" targetFramework="net45" />
  <package id="Ninject.Web.Common.WebHost" version="3.2.3.0" targetFramework="net45" />
  <package id="Ninject.Web.WebApi" version="3.2.4.0" targetFramework="net45" />
  <package id="Owin" version="1.0" targetFramework="net451" />
  <package id="WebActivatorEx" version="2.0.6" targetFramework="net45" />
</packages>

**Comment by scott-xu** [comment]
漏了 Ninject.Web.WebApi.WebHost

**Comment by leshin** [comment]
非常感谢你的热心帮助！我用3.2.3版本的，没有引用Ninject.Web.WebApi.WebHost，怎么没有问题啊。

**Comment by scott-xu** [comment]
从3.2.4开始需要

**Comment by leshin** [comment]
我是部署在IIS，但是使用了OWIN，合适用Ninject.Web.WebApi.OwinHost吗？

**Comment by leshin** [comment]
已解决，非常感谢！
