### ISSUE TITLE
An error occurred when trying to create a controller of type...

### ISSUE THREAD

**Issue by raphaelhudvoy** [ninject/Ninject.Web.WebApi#16]
I installed Ninject Web API 3.2.4 (which is the current version on NuGet Manager) in a new Web API MVC 5 project. After adding and modifying the NinjectWebCommon.cs file in the App_start folder I tried to run some queries using postman. However I keep receiving this error:

![screen shot 2015-03-17 at 20 30 42](https://cloud.githubusercontent.com/assets/2320269/6700444/94dc1adc-cce4-11e4-9209-97ea377d30ff.png)

When I downgrade to  Ninject Web API 3.2.3, I don't get the error and everything works fine. 

I looks like there are some breaking changes in the new version or is there a new way to configure  Ninject Web API 3.2.4?

**Comment by scott-xu** [comment]
Please make sure you installed Ninject.Web.WebApi.WebHost

发自我的 iPhone

**Comment by raphaelhudvoy** [comment]
I added Ninject.Web.WebApi.WebHost and updated the new NinjectWebCommon.cs but I still have the same issue. Everything works fine if I downgrade again to 3.2.3

**Comment by scott-xu** [comment]
Can you zip a sample project and send to me?

发自我的 iPhone

**Comment by raphaelhudvoy** [comment]
Here it is: https://github.com/raphaelhudvoy/sampleWebAPIusingNinject/

Thanks

**Comment by raphaelhudvoy** [comment]
I think I mixup Ninject.Web.WebApi.WebHost and Ninject.Web.Common.WebHost. I uninstall all Ninject package and reinstall  Ninject.Web.WebApi.WebHost with all its dependencies. It seems to work but now I am getting this error
![screen shot 2015-03-18 at 11 25 41](https://cloud.githubusercontent.com/assets/2320269/6712175/97fd3f20-cd61-11e4-98b9-333f0e993e47.png)

**Comment by scott-xu** [comment]
Please make sure all packages are up to date

**Comment by raphaelhudvoy** [comment]
When I run :
Install-Package Ninject.Web.WebApi -Version 3.2.4

I get back the initial error!

**Comment by raphaelhudvoy** [comment]
I am currently have those versions:

Ninject 3.2.2.0
Ninject.Web.Common 3.2.3
Ninject.Web.Common.WebHost  3.2.3
Ninject.Web.WebApi.WebHost 3.2.4
Ninject.Web.WebApi -Version 3.2.4

**Comment by raphaelhudvoy** [comment]
Finally I restarted from scratch following this: http://www.alexzaitzev.pro/2014/11/webapi2-owin-and-ninject.html.

**Comment by scott-xu** [comment]
You didn't install Ninject.Web.WebApi.WebHost
