### ISSUE TITLE
HttpFilters not being injected.

### ISSUE THREAD

**Issue by brazilianldsjaguar** [ninject/Ninject.Web.WebApi#19]
In 3.2.4, the `.BindHttpFilter<IFilter>` method works fine, however the filter is never instantiated or injected.

Recreate:

1. Create a Filter attribute (e.g. an action filter, as in the examples)
2. In a NinjectConfigurator (or wherever your configurations are done), bind the filter w/ the syntax, putting it in whatever scope you'd like:
`container.BindHttpFilter<LogActionFilter>( FilterScope.Controller );`
3. Add breakpoints to the Filter's constructor or other methods
3. Run the project
4. Hit a controller (e.g. "api/customers"). Notice that the constructor is never called.

Downgrade to 3.2.2, repeat steps above, notice constructor is called.

I ran a diff between 3.2.2 and 3.2.4, and apparently the offending line is this one:

    this.Bind<HttpConfiguration>( ).ToMethod( ctx => GlobalConfiguration.Configuration );

Proof:

1. Recreate problem with 3.2.4 per steps above
2. As the very first thing you bind (before binding filters), add this:
`container.Bind<HttpConfiguration>( ).ToMethod( ctx => GlobalConfiguration.Configuration );`
3. Repeat steps, notice constructor is now called.

Not sure why the bind to HttpConfiguration was removed, but it apparently broke HttpFilter injection.

**Comment by brazilianldsjaguar** [comment]
(what I didn't check was to see if this line really was removed in 3.2.3, I just did a general diff of the two versions and that was what I confirmed to be the offender)

**Comment by scott-xu** [comment]
Please install nuget package: Ninject.Web.WebApi.WebHost

**Comment by scott-xu** [comment]
https://github.com/ninject/Ninject.Web.WebApi/blob/master/ReleaseNotes.md

**Comment by brazilianldsjaguar** [comment]
Scott,

Thanks for the response! Ninject.Web.Common.WebHost was (and has been)
installed - all the steps I listed in the 'repeat' process happened w/
WebHost installed as well.

On Thu, Jul 9, 2015 at 2:02 AM, Scott Xu <notifications@github.com> wrote:

> Please install nuget package: Ninject.Web.WebApi.WebHost
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ninject/Ninject.Web.WebApi/issues/19#issuecomment-119880871>
> .
>



-- 
*Matthew Johnson*
*brazilianldsjaguar@gmail.com <brazilianldsjaguar@gmail.com>*
General Programming Consultant

**Comment by scott-xu** [comment]
It is Ninject.Web.WebApi.WebHost but not Ninject.Web.Common.WebHost

**Comment by brazilianldsjaguar** [comment]
Yes, you're right! I apologize, once I got Ninject.Web.WEBAPI.WebHost in there, it worked as expected. Thanks!
