### ISSUE TITLE
Nuget package Ninject.Web.WebApi.WebHost: Error activating HttpConfiguration v3.2.4

### ISSUE THREAD

**Issue by smaglio81** [ninject/Ninject.Web.WebApi#24]
Hello,

It looks like the nuget package for [Ninject.Web.WebApi.Host v3.2.4](https://www.nuget.org/packages/Ninject.Web.WebApi.WebHost/) has a dependency on Ninject.Web.WebApi with a range of (>= 3.2.0 && < 3.3.0). But, when I let nuget pull in v3.2.0 of .WebApi I get the `Ninject.ActivationException` described in [this stackoverflow post](http://stackoverflow.com/questions/28711963/ninject-activationexception-thrown-only-on-first-web-request-webapi-2-owin-3).

If I update the .WebApi nuget reference to v3.2.4, then the exception no longer occurs.

I was wondering if it's possible to update [Ninject.Web.WebApi.Host v3.2.4](https://www.nuget.org/packages/Ninject.Web.WebApi.WebHost/)'s nuget package to have a minimum version range of v3.2.4 on .WebApi?

**Comment by scott-xu** [comment]
Fixed in 3.3
