### ISSUE TITLE
Self/Owin Hosting InRequestScope broken without ContextPreservation extension, 

### ISSUE THREAD

**Issue by cmeyertons** [ninject/Ninject.Web.WebApi#26]
I'm currently writing integration tests for my ASP.NET Web API.

In the Web API project, we are using Ninject.Web.WebApi.WebHost and InRequestScope works great.

In our integration test project, we are using ASP.NET WebAPI in-memory testing, passing a Ninject bootstrapped `HttpSelfHostConfiguration` to an `HttpServer`:

`

		private static string _url = "http://localhost:12345/";

		private static HttpSelfHostConfiguration Config { get; set; }

		static WebApi()
		{
			Config = new HttpSelfHostConfiguration(_url);
			WebApiConfig.Register(Config);

			Config.IncludeErrorDetailPolicy = IncludeErrorDetailPolicy.Always;

			var selfHost = new NinjectSelfHostBootstrapper(CreateKernel, Config);
		}

		public static async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request)
		{
			var client = new HttpClient(new HttpServer(Config));

			HttpResponseMessage response;

			try
			{
				response = await client.SendAsync(request, new CancellationTokenSource().Token);
			}
			catch (HttpResponseException ex)
			{
				response = ex.Response;
			}

			return response;
		}

		private static IKernel CreateKernel()
		{
			var kernel = NinjectWebCommon.CreateKernel();

			return kernel;
		}

`
We are using Entity Framework and binding the DbContext in the request scope:

`
       public ContractsController(IContractBL contractBL)
        {
			this._BusinessLayer = contractBL;
        }
`

`this.Bind<IContractBL>().To<ContractBL>().Intercept().With<IDataLayerInterceptor>();`
`this.Bind<IContractRepo>().To<ContractRepo>().Intercept().With<IIntegrationLayerInterceptor>();`
`this.Bind<PartnerContext>().ToSelf().InRequestScope();`

`

When I do not have the ContextPreservation extension installed, the `SelfHostWebApiRequestScopeProvider.GetRequestScope` throws an `UnknownScopeException`.

I see that both Owin and Self-Host both use NamedScope under the covers to do the request scoping.  Should ContextPreservation be added as a dependency to these solutions?

Also, as an aside, would the named scoping solution work for WebHosting?  If so, could the RequestScope code be pulled down into Ninject.Web.WebApi and allow all hosting solutions to leverage the same code?

**Comment by scott-xu** [comment]
Ninject.Web.WebApi 3.3.1 fixed the issue. See the sample applications please.
