### ISSUE TITLE
InRequestmode doesn't work

### ISSUE THREAD

**Issue by Loppone** [ninject/Ninject.Web.WebApi#30]
I created a project with EF6 + Ninject + Owin. I realized that Ninject InRequestScope doesn't work, infact, in a single Web Api request the constructor of my DBContext derived class fires more than once.

The Startup file of my web api project is like:

public void Configuration(IAppBuilder app)
{
    ConfigureOAuth(app);
    HttpConfiguration config = new HttpConfiguration();
    WebApiConfig.Register(config);
    app.UseWebApi(config);

    app.UseNinjectMiddleware(CreateKernel).UseNinjectWebApi(config);
}

private static IKernel CreateKernel()
{
    // I have my Ninject module in a separate assembly
    var kernel = new StandardKernel(new Core.Ioc.AutoBotMapper());

    GlobalConfiguration.Configuration.DependencyResolver = new NinjectDependencyResolver(kernel);

    return kernel;
}
My Module:

public class AutoBotMapper : NinjectModule
{
    private readonly ILog _logger = LogManager.GetLogger("CORE");

    public override void Load()
    {
        // Contesto is my DBContext
        Bind<Contesto>().ToSelf().InRequestScope(); 

        // Other Binds
        Bind<ITournamentServiceFactory>().ToFactory();
        Bind<ITournamentCloser>().To<TournamentCloser>();

        ...
    }
}

**Comment by scott-xu** [comment]
It looks like you are hosting your project using WebHost (IIS). Please use `GlobalConfiguration.Configuration` in your startup file instead of instantiating a new instance. You don’t need to explicitly set `config.DependencyResolver`. Please use the latest Ninject.Web.WebApi.WebHost.

**Comment by scott-xu** [comment]
Please also remember to call `DynamicModuleUtility.RegisterModule(typeof(OnePerRequestHttpModule));` when start the web application. Check the sample application please.

**Comment by Loppone** [comment]
I'm trying to follow the sample, but I have a problem with NewtonSoft.Json. I use Microsoft.Owin.Security.OAuth that requires the version >= 10.0.1, but i see Ninject need version 6.0.0, so the error:
Unable to load file or assembly 'Newtonsoft.Json, Version=6.0.0.0...
Are OAuth and Ninject incompatible?

**Comment by Loppone** [comment]
I follow the code in the sample "Owin-SampleApplication" so i changed my code like this:

NinjectWebCommon.cs:

	[assembly: WebActivatorEx.PreApplicationStartMethod(typeof(SampleApplication.App_Start.NinjectWebCommon), "Start")]

	namespace SampleApplication.App_Start
	{
		using Microsoft.Web.Infrastructure.DynamicModuleHelper;
		using Ninject.Web.Common.WebHost;

		/// <summary>
		/// Bootstrapper for the application.
		/// </summary>
		public static class NinjectWebCommon
		{
			/// <summary>
			/// Starts the application
			/// </summary>
			public static void Start()
			{
				DynamicModuleUtility.RegisterModule(typeof(OnePerRequestHttpModule));
			}
		}
	}

Startup.cs


	[assembly: OwinStartup(typeof(Startup))]
	namespace TempApi
	{
		public class Startup
		{
			public void Configuration(IAppBuilder app)
			{
				app.UseCors(Microsoft.Owin.Cors.CorsOptions.AllowAll);
				ConfigureOAuth(app);
				HttpConfiguration config = new HttpConfiguration();
				config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
				config.Formatters.JsonFormatter.UseDataContractJsonSerializer = false;
				WebApiConfig.Register(config);
				SwaggerConfig.Register(config);

				app.UseWebApi(config);

				app.UseNinject(CreateKernel);
				app.UseWebApi(GlobalConfiguration.Configuration);
			}

			public void ConfigureOAuth(IAppBuilder app)
			{
				OAuthAuthorizationServerOptions oauthOptions = new OAuthAuthorizationServerOptions()
				{
					AllowInsecureHttp = true,
					TokenEndpointPath = new PathString("/oauth/token"),
					AccessTokenExpireTimeSpan = TimeSpan.FromDays(1),
					Provider = new SimpleAuthorizationServerProvider(),
					RefreshTokenProvider = new SimpleRefreshTokenProvider()
				};

				app.UseOAuthAuthorizationServer(oauthOptions);
				app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions());
			}

			private static IKernel CreateKernel()
			{
				var kernel = new StandardKernel(new Core.Ioc.AutoBotMapper());

				return kernel;
			}
		}
	}

In another assembly my Ninject module:

	namespace Core.Ioc
	{
		public class AutoBotMapper : NinjectModule
		{

			public override void Load()
			{
			 
				Bind<Contesto>().ToSelf().InRequestScope();
				...			
			}
		}
	}

It seems it can't resolve because it ask me a parameterless constructor...

**Comment by Loppone** [comment]
Adding a GlobalConfiguration.Configuration.DependencyResolver:

	private static IKernel CreateKernel()
	{
		var kernel = new StandardKernel(new Core.Ioc.AutoBotMapper());

		GlobalConfiguration.Configuration.DependencyResolver = new NinjectDependencyResolver(kernel);
	 
		return kernel;
	}

I get this error: "Error activating ModelValidatorProvider using binding from ModelValidatorProvider to NinjectDefaultModelValidatorProvider..."

**Comment by scott-xu** [comment]
You are calling `UseWebApi` twice in your startup.cs
Please use `GlobalConfiguration.Configuration` in your startup file **instead** of instantiating a new instance. You don’t need to explicitly set `config.DependencyResolver`. Please use the latest Ninject.Web.WebApi.WebHost.

**Comment by Loppone** [comment]
It works, thanks. I just realize you meant GlobalConfiguration.Configuration instead of a new HttpConfiguration: my fault!
